routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ExamController@index')->name('home');
Route::get('home', 'ExamController@index')->name('home.index');
Route::get('exam', 'ExamController@index')->name('exam.index');
Route::get('show/{id}', 'ExamController@show')->name('exam.show');
Route::get('cert/{key}', 'CertController@show')->name('cert.index');
Route::post('cert/{key}', 'CertController@verify')->name('cert.verify');
Route::get('problem', 'ProblemController@index')->name('problem.index');
Route::get('problem/{id}', 'ProblemController@show')->name('problem.show');

/**
 * Member
 */
Route::group([
    'middleware' => ['auth'],
], function (){
    Route::post('exam/{id}/signup', 'ExamController@store')->name('exam.store');
    //    Route::get('exam/{id}/certificate', 'ExamController@certificate')->name('exam.certificate');
    Route::get('exam/{id}/cancel', 'ExamController@cancel')->name('exam.cancel');
    Route::get('profile', 'PorfileController@index')->name('profile.index');
    Route::post('profile/passwd', 'PorfileController@passwd')->name('profile.passwd');
});

/**
 * Authentication Routes
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('email-verification/error',
    'Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}',
    'Auth\RegisterController@getVerification')->name('email-verification.check');

/**
 * API
 */
Route::group([
    'prefix'    => 'api',
    'as'        => 'api.',
    'namespace' => 'Api'
], function (){
    Route::get('exam', 'ExamController@all')->name('exam');
    Route::get('dept', 'DeptController@get')->name('dept');
    Route::get('problem', 'ProblemController@all')->name('problem');
});


/**
 * Dashboard
 */
Route::group([
    'middleware' => ['auth', 'role:admin'],
], function (){
    Route::get('api/signup/{id}', 'Api\ExamController@signup')->name('api.signup')->where('id', '[0-9]+');
    Route::get('api/user/all', 'Api\UserController@all')->name('api.user.all');
    Route::get('api/school/all', 'Api\SchoolController@all')->name('api.school.all');
    Route::get('api/problems', 'Api\ProblemController@dashboard')->name('api.problem.all');
    Route::get('api/exams', 'Api\ExamController@admin')->name('api.exam.all');

    Route::group([
        'prefix'    => 'dashboard',
        'as'        => 'dashboard.',
        'namespace' => 'Dashboard'
    ], function (){
        Route::post('exam/threshold/{id}', 'ExamController@update_threshold')->name('exam.threshold')->where('id',
            '[0-9]+');

        Route::get('exam-export/list/{id}', 'ExamExportController@index')->name('exam-export.list');
        Route::get('exam-export/pc2/{id}', 'ExamExportController@pc2')->name('exam-export.pc2');

        Route::post('exam/score/enter/{id}', 'ExamScoreController@index')->name('exam-score.index');
        Route::post('exam/score/update/{id}', 'ExamScoreController@store')->name('exam-score.store');
        Route::get('exam/score/cert/{id}', 'ExamScoreController@cert')->name('exam-score.cert');
        Route::get('exam/cert/{id}', 'ExamScoreController@cert_file')->name('exam-score.cert_file');

        Route::resource('grade-ability', 'GradeAbilityController')->only(['edit', 'update']);
        Route::resource('exam-problem', 'ExamProblemController',
            ['parameters' => ['exam-problem' => 'id']])->only(['show', 'update', 'destroy']);
        Route::resource('exam', 'ExamController');
        Route::resource('user', 'UserController');
        Route::resource('school', 'SchoolController');
        Route::resource('problem', 'ProblemController')->only(['index', 'show']);
    });

});

Route::get('datatable', 'DatatableController')->name('js.datatable');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DataTables;
use App\User;

class UserController extends Controller
{
    public function all()
    {
        $users      = User::all();
        $datatables = collect();


        foreach ($users as $key => $user) {
            $datatables->push([
                'id' => $user->id,
                'student_id' => $user->student_id,
                'username'   => $user->username,
                'name_zh_tw' => $user->name_zh_tw,
                'verified'   => $user->verified ? 'Y' : 'N',
            ]);
        }

        return DataTables::of($datatables)
            ->addColumn('action', function ($datatable){
                $return= '<a class="btn btn-sm btn-info" href="' . route('dashboard.user.edit', $datatable[ 'id' ]) . '">編輯</a>';
                return $return;
            })
            ->make(true);
    }
}

app/Http/Controllers/Dashboard/ExamController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\CodingLang;
use App\Exam;
use App\ExamCodingLang;
use App\ExamSignup;
use App\Http\Requests\ExamStore;
use App\Http\Controllers\Controller;
use App\Http\Requests\ExamThresholdUpdate;
use Carbon\Carbon;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $exams = Exam::all();

        return view('dashboard.exam.index', compact('exams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $langs = CodingLang::all();

        return view('dashboard.exam.create', compact('langs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ExamStore $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(ExamStore $request)
    {
        $exam                 = new Exam();
        $exam->name           = $request->input('name');
        $exam->place          = $request->input('place');
        $exam->desc           = $request->input('desc') ?? '';
        $exam->time_start     = Carbon::parse($request->input('time_start'));
        $exam->time_end       = Carbon::parse($request->input('time_end'));
        $exam->signup_start   = Carbon::parse($request->input('signup_start'));
        $exam->signup_end     = Carbon::parse($request->input('signup_end'));
        $exam->pass_threshold = null;
        $exam->publish_time   = Carbon::parse($request->input('publish_time'));
        $exam->problem_note   = $request->input('problem_note') ?? '';
        $exam->save();

        $coding = [];

        foreach ($request->input('exam_lang') as $key => $exam_lang) {
            $coding[ $key ] = [
                'exam_id' => $exam->id,
                'lang_id' => $exam_lang,
            ];
        }

        return ExamCodingLang::insert($coding) ? redirect()->route('dashboard.exam.index')->with('msg',
            '建立考試成功') : redirect()->route('dashboard.exam.index')->with('error_msg', '建立考試失敗');

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $exam = Exam::findOrFail($id);

        $langs = ExamCodingLang::with('lang')->where('exam_id', $id)->get()->keyBy('lang_id');

        $signups = ExamSignup::whereExamId($exam->id)->get();
        $pc2     = ExamSignup::whereExamId($exam->id)->whereNotNull('pc2_account')->count();

        $data = $signups->groupBy(function ($item, $key) {
            return $item['solve_problem'];
        })->map(function ($item, $key) {
            return collect($item)->count();
        });

        return view('dashboard.exam.show', compact('exam', 'langs', 'signups', 'pc2', 'data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exam = Exam::findOrFail($id);

        $langs = CodingLang::all();

        $coding = ExamCodingLang::whereExamId($id)->get()->pluck('lang_id');

        return view('dashboard.exam.edit', compact('exam', 'langs', 'coding'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(ExamStore $request, $id)
    {
        $exam                 = Exam::findOrFail($id);
        $exam->name           = $request->input('name');
        $exam->place          = $request->input('place');
        $exam->desc           = $request->input('desc') ?? '';
        $exam->time_start     = Carbon::parse($request->input('time_start'));
        $exam->time_end       = Carbon::parse($request->input('time_end'));
        $exam->signup_start   = Carbon::parse($request->input('signup_start'));
        $exam->signup_end     = Carbon::parse($request->input('signup_end'));
        $exam->pass_threshold = $request->input('pass_threshold');
        $exam->publish_time   = Carbon::parse($request->input('publish_time'));
        $exam->problem_note   = $request->input('problem_note') ?? '';
        $exam->save();

        ExamCodingLang::whereExamId($id)->delete();

        $coding = [];
        foreach ($request->input('exam_lang') as $key => $exam_lang) {
            $coding[ $key ] = [
                'exam_id' => $exam->id,
                'lang_id' => $exam_lang,
            ];
        }

        return ExamCodingLang::insert($coding) ? redirect()->route('dashboard.exam.edit', $id)->with('msg',
            '更新考試成功') : redirect()->route('dashboard.exam.edit', $id)->with('error_msg', '更新考試失敗');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function update_threshold(ExamThresholdUpdate $request, $id)
    {
        $exam                 = Exam::findOrFail($id);
        $exam->pass_threshold = $request->input('pass_threshold');

        $msg = ['success' => 0, 'message' => '更新通過門檻失敗', 'status' => 'error'];
        if ($exam->save()) {
            $msg = ['success' => 1, 'message' => '更新通過門檻成功', 'status' => 'success'];
        }

        return response()->json($msg);;
    }
}

app/Http/Controllers/Dashboard/ExamExportController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Exam;
use App\ExamSignup;
use App\Http\Controllers\Controller;
use Excel;

class ExamExportController extends Controller
{
    public function index($id)
    {
        $exam    = Exam::findOrFail($id);
        $signups = ExamSignup::with(['school', 'dept', 'code'])->whereExamId($exam->id)->get();

        $lists = collect();
        $lists->push(['學校', '學系', '學制', '學號', '姓名', '程式語言', '報名時間']);

        foreach ($signups as $signup) {
            switch ($signup->edu_level) {
                case 'B':
                    $edu_level = '大學部';
                    break;
                case 'M':
                    $edu_level = '碩士班';
                    break;
                default:
                case 'D':
                    $edu_level = '博士班';
                    break;
            }
            $lists->push([
                $signup->school->name,
                $signup->dept->name,
                $edu_level,
                $signup->student_id,
                $signup->name_zh_tw,
                $signup->code->lang,
                $signup->created_at->toDateTimeString()
            ]);
        }
        $lists = $lists->toArray();

        Excel::create($exam->name . ' - 報名名單(' . now()->toDateTimeString() . ')', function ($excel) use ($lists, $exam){
            $excel->setTitle($exam->name . ' - 報名名單')
                ->setCreator(config('asiacode.site_name'))
                ->setCompany(config('asiacode.site_name'))
                ->setManager(config('asiacode.site_name'))
                ->setLastModifiedBy(config('asiacode.site_name'));

            $excel->sheet('報名名單', function ($sheet) use ($lists){
                $sheet->rows($lists)->setAutoSize(true);
            });
        })->export('xlsx');
    }


    public function pc2($id)
    {
        $exam = Exam::findOrFail($id);

        $this->generate_pc2($id);

        $signups = ExamSignup::with(['school', 'dept', 'code'])->whereExamId($exam->id)->get();


        $lists = collect();
        $lists->push([
            'site',
            'account',
            'displayname',
            'password',
            'group',
            'permdisplay',
            'permlogin',
            'externalid',
            'alias',
            'permpassword',
            'longschoolname',
            'shortschoolname',
            'countrycode'
        ]);

        foreach ($signups as $signup) {
            $lists->push([
                $exam->id,
                'team' . $signup->pc2_account,
                $signup->student_id,
                $signup->pc2_password,
                '',
                'TRUE',
                'TRUE',
                $exam->id*1000+$signup->pc2_account,
                $signup->student_id,
                'FALSE',
                '',
                '',
                'XXX'
            ]);
        }

        $lists = $lists->toArray();

        return response()
            ->view('dashboard.exam-export.pc2', compact('lists'), 200)
            ->header('Content-Disposition', 'attachment; filename="site'.$exam->id . '.txt"')
            ->header('Content-Type', 'text/plain');
    }

    protected function generate_pc2($id)
    {
        $exam = Exam::findOrFail($id);

        $signups = ExamSignup::whereExamId($exam->id)->get();

        $size    = count($signups);
        $numbers = range(1, $size);
        shuffle($numbers);

        $characters       = '23456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'; //去除 1, i, l, I, o, 0, O
        $characters_array = str_split($characters);


        foreach ($signups as $key => $signup) {
            $signup->pc2_account  = $numbers[ $key ];
            $signup->pc2_password = join('', array_random($characters_array, env('PC2_PASSWORD_LENGTH')));
            $signup->save();
        }

    }
}

app/Http/Controllers/Dashboard/ExamProblemController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Exam;
use App\ExamProblem;
use App\Problem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ExamProblemController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $exam = Exam::findOrFail($id);
        $problems = Problem::all();
        $exam_problems = ExamProblem::with('problem')->whereExamId($id)->get();

        $problem_id =  $exam_problems->pluck('problem_id');
        $show = [];
        foreach ($problem_id as $pid){
            $show[$pid] = true;
        }

        return view('dashboard.exam-problem.show', compact('exam','exam_problems', 'problems','show'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $exam = Exam::findOrFail($id);

        foreach ($request->input('problem_id') as $problem_id){
            ExamProblem::create([
                'exam_id' => $exam->id,
                'problem_id' => $problem_id,
            ]);
        }

        return redirect()->route('dashboard.exam-problem.show', $exam->id)->with('msg', '考試題目設定完畢');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $msg = ['success' => 0, 'message' => '刪除考試題目失敗', 'status' => 'error'];
        $exam = Exam::whereId($id)->first();

        if (empty($exam)) {
            return response()->json($msg);
        }

        if( ExamProblem::whereExamId($exam->id)->whereProblemId($request->query('problem_id'))->delete() ){
            $msg = ['success' => 1, 'message' => '成功刪除考試題目', 'status' => 'success'];
        }else{
            $msg = ['success' => 0, 'message' => '刪除考試題目失敗', 'status' => 'error'];
        }

        return response()->json($msg);
    }
}

resources/views/dashboard/user/edit.blade.php
@extends('layouts.app')

@section('page-title','使用者資料編輯')

@section('content')
	@includeWhen($errors->any(), 'component.alert-validation', ['errors' => $errors])
	<form method="POST" action="{{ route('dashboard.user.update', $user->id) }}">
		{{ csrf_field() }}
		{{ method_field('PUT') }}
		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="username">帳號*</label>
				<input id="username" type="text" class="form-control-plaintext {{ $errors->has('username') ? 'is-invalid' : '' }}" name="username" value="{{ old('username', $user->username) }}">
				@if ($errors->has('username'))
					<div class="invalid-feedback"> {{ $errors->first('username') }} </div>
				@endif
			</div>

			<div class="form-group col-md-6">
				<label for="sex">性別*</label>
				<div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" class="custom-control-input" id="sex_0" name="sex" required value="0"{{ old('sex', $user->sex) == 0 ? 'checked' : '' }}>
						<label class="custom-control-label" for="sex_0">女</label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" class="custom-control-input" id="sex_1" name="sex" required value="1"{{ old('sex', $user->sex) == 1 ? 'checked' : '' }}>
						<label class="custom-control-label" for="sex_1">男</label>
					</div>
				</div>
				@if ($errors->has('last_name_en'))
					<div class="invalid-feedback"> {{ $errors->first('last_name_en') }} </div>
				@endif
			</div>

			<div class="form-group col-md-6">
				<label for="student_id">學號*</label>
				<input id="student_id" type="text" class="form-control {{ $errors->has('student_id') ? 'is-invalid' : '' }}" name="student_id" value="{{ old('student_id', $user->student_id) }}" v-model="student_id">
				@if ($errors->has('student_id'))
					<div class="invalid-feedback"> {{ $errors->first('student_id') }} </div>
				@endif
			</div>

			<div class="form-group col-md-6">
				<label for="name_zh_tw">姓名*</label>
				<input id="name_zh_tw" type="text" class="form-control {{ $errors->has('name_zh_tw') ? 'is-invalid' : '' }}" name="name_zh_tw" value="{{ old('name_zh_tw', $user->name_zh_tw) }}">
				@if ($errors->has('name_zh_tw'))
					<div class="invalid-feedback"> {{ $errors->first('name_zh_tw') }} </div>
				@endif
			</div>

			<div class="form-group col-md-6">
				<label for="first_name_en">英文名*</label>
				<input id="first_name_en" type="text" class="form-control {{ $errors->has('first_name_en') ? 'is-invalid' : '' }}" name="first_name_en" value="{{ old('first_name_en', $user->first_name_en) }}">
				@if ($errors->has('first_name_en'))
					<div class="invalid-feedback"> {{ $errors->first('first_name_en') }} </div>
				@endif
			</div>
			<div class="form-group col-md-6">
				<label for="last_name_en">英文姓*</label>
				<input id="last_name_en" type="text" class="form-control {{ $errors->has('last_name_en') ? 'is-invalid' : '' }}" name="last_name_en" value="{{ old('last_name_en', $user->last_name_en) }}">
				@if ($errors->has('last_name_en'))
					<div class="invalid-feedback"> {{ $errors->first('last_name_en') }} </div>
				@endif
			</div>

			<div class="form-group col-md-4">
				<label for="school_id">學校*</label>
				<select class="form-control {{ $errors->has('school_id') ? 'is-invalid' : '' }}" name="school_id" id="school_id" v-model="school_id" v-on:change="getDepts">
					<option value="">請先選擇學校</option>
					<option v-for="school in schools" v-bind:value="school.id">
						@{{ school.name }}
					</option>
				</select>
				@if ($errors->has('school_id'))
					<div class="invalid-feedback"> {{ $errors->first('school_id') }} </div>
				@endif
			</div>
			<div class="form-group col-md-4">
				<label for="dept_id">學系*</label>
				<select class="form-control {{ $errors->has('dept_id') ? 'is-invalid' : '' }}" name="dept_id" id="dept_id" v-model="dept_id">
					<option value="">請先選擇學系</option>
					<option v-for="dept in depts" v-bind:value="dept.id">
						@{{ dept.name }}
					</option>
				</select>
				@if ($errors->has('dept_id'))
					<div class="invalid-feedback"> {{ $errors->first('dept_id') }} </div>
				@endif
			</div>
			<div class="form-group col-md-4">
				<label for="edu_level">學制*</label>
				<div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" class="custom-control-input" id="edu_level_b" name="edu_level" required value="B"{{ old('edu_level', $user->edu_level) == 'B' ? 'checked' : '' }}>
						<label class="custom-control-label" for="edu_level_b">大學部</label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" class="custom-control-input" id="edu_level_m" name="edu_level" required value="M"{{ old('edu_level', $user->edu_level) == 'M' ? 'checked' : '' }}>
						<label class="custom-control-label" for="edu_level_m">碩士班</label>
					</div>
					<div class="custom-control custom-radio custom-control-inline">
						<input type="radio" class="custom-control-input" id="edu_level_d" name="edu_level" required value="D"{{ old('edu_level', $user->edu_level) == 'D' ? 'checked' : '' }}>
						<label class="custom-control-label" for="edu_level_d">博士班</label>
					</div>
				</div>
				@if ($errors->has('edu_level'))
					<div class="invalid-feedback"> {{ $errors->first('edu_level') }} </div>
				@endif
			</div>

			<div class="form-group col-md-9">
				<label for="email">信箱*</label>
				<input id="email" type="text" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" name="email" value="{{ old('email', $user->email) }}">
				@if ($errors->has('email'))
					<div class="invalid-feedback"> {{ $errors->first('email') }} </div>
				@endif
			</div>

			<div class="form-group col-md-3">
				<div>
					<div class="custom-control custom-checkbox">
						<input type="checkbox" class="custom-control-input {{ $errors->has('verified') ? 'is-invalid' : '' }}" id="verified" name="verified" value="1" {{ old('verified', $user->verified)? 'checked' : '' }}>
						<label class="custom-control-label" for="verified">信箱認證</label>
					</div>
				</div>
				@if ($errors->has('verified'))
					<div class="invalid-feedback"> {{ $errors->first('verified') }} </div>
				@endif
			</div>
		</div>

		<button type="submit" class="btn btn-primary">修改</button>
	</form>
@endsection

@push('script')
	<script>
		const app = new Vue({
			el: '#app',
			data: {
				student_id: '{{ old('student_id', $user->student_id) }}',
				student_email: '',
				schools: @json($schools),
				school_id: '{{ old('school_id', $user->school_id) }}',
				dept_id: '{{ old('dept_id', $user->dept_id) }}',
				depts: []
			},
			mounted: function () {
				this.getDepts();
			},
			methods: {
				getDepts: function () {
					const self = this;
					if (this.school_id !== '') {
						this.student_email = JSON.parse(JSON.stringify(this.schools))[this.school_id].student_email;
					}
					axios.get('{{ route('api.dept') }}?school_id=' + self.school_id).then(function (response) {
						if (response.status === 200) {
							self.depts = response.data;
						}
					});
				},
			}
		});

	</script>
@endpush

resources/views/dashboard/user/index.blade.php
@extends('layouts.app')

@section('page-title','使用者管理')

@section('content')
	<table id="users" class="table table-striped table-bordered">
		<thead>
		<tr>
			<th>學號</th>
			<th>帳號</th>
			<th>姓名</th>
			<th>信箱認證</th>
			<th>操作</th>
		</tr>
		</thead>
	</table>
@endsection

@push('script')
	<script>
		$(function () {
			$('#users').DataTable({
				processing: true,
				serverSide: true,
				ajax: '{{ route('api.user.all') }}',
				columns: [
					{data: 'student_id'},
					{data: 'username'},
					{data: 'name_zh_tw'},
					{data: 'verified'},
					{data: 'action', name: 'action', orderable: false, searchable: false}
				],
				language: {
					"url": "{{ route('js.datatable') }}"
				}
			});
		});
	</script>
@endpush