routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ExamController@index')->name('home');
Route::get('home', 'ExamController@index')->name('home.index');
Route::get('exam', 'ExamController@index')->name('exam.index');
Route::get('show/{id}', 'ExamController@show')->name('exam.show');
Route::get('cert/{key}', 'CertController@show')->name('cert.index');
Route::post('cert/{key}', 'CertController@verify')->name('cert.verify');
Route::get('problem', 'ProblemController@index')->name('problem.index');
Route::get('problem/{id}', 'ProblemController@show')->name('problem.show');

/**
 * Member
 */
Route::group([
    'middleware' => ['auth'],
], function (){
    Route::post('exam/{id}/signup', 'ExamController@store')->name('exam.store');
    //    Route::get('exam/{id}/certificate', 'ExamController@certificate')->name('exam.certificate');
    Route::get('exam/{id}/cancel', 'ExamController@cancel')->name('exam.cancel');
    Route::get('profile', 'PorfileController@index')->name('profile.index');
    Route::post('profile/passwd', 'PorfileController@passwd')->name('profile.passwd');
});

/**
 * Authentication Routes
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('email-verification/error',
    'Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}',
    'Auth\RegisterController@getVerification')->name('email-verification.check');

/**
 * API
 */
Route::group([
    'prefix'    => 'api',
    'as'        => 'api.',
    'namespace' => 'Api'
], function (){
    Route::get('exam', 'ExamController@all')->name('exam');
    Route::get('dept', 'DeptController@get')->name('dept');
    Route::get('problem', 'ProblemController@all')->name('problem');
});


/**
 * Dashboard
 */
Route::group([
    'middleware' => ['auth', 'role:admin'],
], function (){
    Route::get('api/signup/{id}', 'Api\ExamController@signup')->name('api.signup')->where('id', '[0-9]+');
    Route::get('api/user/all', 'Api\UserController@all')->name('api.user.all');
    Route::get('api/school/all', 'Api\SchoolController@all')->name('api.school.all');
    Route::get('api/problems', 'Api\ProblemController@dashboard')->name('api.problem.all');
    Route::get('api/exams', 'Api\ExamController@admin')->name('api.exam.all');

    Route::group([
        'prefix'    => 'dashboard',
        'as'        => 'dashboard.',
        'namespace' => 'Dashboard'
    ], function (){
        Route::post('exam/threshold/{id}', 'ExamController@update_threshold')->name('exam.threshold')->where('id',
            '[0-9]+');

        Route::get('exam-export/list/{id}', 'ExamExportController@index')->name('exam-export.list');
        Route::get('exam-export/pc2/{id}', 'ExamExportController@pc2')->name('exam-export.pc2');

        Route::post('exam/score/enter/{id}', 'ExamScoreController@index')->name('exam-score.index');
        Route::post('exam/score/update/{id}', 'ExamScoreController@store')->name('exam-score.store');
        Route::get('exam/score/cert/{id}', 'ExamScoreController@cert')->name('exam-score.cert');
        Route::get('exam/cert/{id}', 'ExamScoreController@cert_file')->name('exam-score.cert_file');

        Route::resource('grade-ability', 'GradeAbilityController')->only(['edit', 'update']);
        Route::resource('exam-problem', 'ExamProblemController',
            ['parameters' => ['exam-problem' => 'id']])->only(['show', 'update', 'destroy']);
        Route::resource('exam', 'ExamController');
        Route::resource('user', 'UserController');
        Route::resource('school', 'SchoolController');
        Route::resource('problem', 'ProblemController')->only(['index', 'show']);
    });

});

Route::get('datatable', 'DatatableController')->name('js.datatable');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Http/Controllers/Api/ExamController.php
<?php

namespace App\Http\Controllers\Api;

use App\Exam;
use App\ExamCodingLang;
use App\ExamSignup;
use App\Http\Controllers\Controller;
use DataTables;

class ExamController extends Controller
{
    public function all()
    {
        $exams      = Exam::all();
        $datatables = collect();

        foreach ($exams as $key => $exam) {
            $datatables->push([
                'index'       => $key + 1,
                'name'        => '<a href="' . route('exam.show', $exam->id) . '">' . $exam->name . '</a>',
                'time'        => $exam->time_start->format('Y-m-d H:i') . ' ~ ' . $exam->time_end->format('Y-m-d H:i'),
                'signup_time' => $exam->signup_start->format('Y-m-d H:i') . ' ~ ' . $exam->signup_end->format('Y-m-d H:i'),
            ]);
        }

        return DataTables::of($datatables)->rawColumns(['name'])->make(true);
    }

    public function admin()
    {
        $exams      = Exam::all();
        $datatables = collect();

        foreach ($exams as $key => $exam) {
            $datatables->push([
                'index'       => $exam->id,
                'name'        => $exam->name,
                'time'        => $exam->time_start->format('Y-m-d H:i') . ' ~ ' . $exam->time_end->format('Y-m-d H:i'),
                'signup_time' => $exam->signup_start->format('Y-m-d H:i') . ' ~ ' . $exam->signup_end->format('Y-m-d H:i'),
            ]);
        }

        return DataTables::of($datatables)->addColumn('action', function ($datatable){
            $return = '<div class="btn-group" role="group">';
            $return.= '<a class="btn btn-success" href="' . route('dashboard.exam.edit', $datatable[ 'index' ]) . '">修改</a>';
            $return.= '<a class="btn btn-secondary" href="' . route('dashboard.exam.show', $datatable[ 'index' ]) . '">名單</a>';
            $return.= '<a class="btn btn-info" href="' . route('dashboard.exam-problem.show', $datatable[ 'index' ]) . '">題目設定</a>';
            $return.= '</div>';
            return $return;
        })->rawColumns(['action'])->make(true);
    }

    public function signup($id)
    {
        $signups    = ExamSignup::whereExamId($id)->get();
        $datatables = collect();

        $langs = ExamCodingLang::with('lang')->where('exam_id', $id)->get()->keyBy('lang_id');
        foreach ($signups as $key => $signup) {
            $datatables->push([
                'index'         => $key + 1,
                'student_id'    => $signup->student_id,
                'name_zh_tw'    => $signup->name_zh_tw,
                'name_en'       => $signup->first_name_en . ' ' . $signup->last_name_en,
                'lang'          => $langs[ $signup->lang_id ]->lang->lang,
                'solve_problem' => $signup->solve_problem,
                'cert_id'       => $signup->cert_id,
                'created_at'    => optional($signup->created_at)->toDateTimeString(),
                'deleted_at'    => optional($signup->deleted_at)->toDateTimeString(),
                'has_pc_2'      => !is_null($signup->pc2_account),
            ]);
        }

        return DataTables::of($datatables)->setRowClass(function ($signup){
            return $signup[ 'has_pc_2' ] ? '' : 'bg-danger';
        })->make(true);
    }
}

app/Http/Controllers/Dashboard/ExamController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\CodingLang;
use App\Exam;
use App\ExamCodingLang;
use App\ExamSignup;
use App\Http\Requests\ExamStore;
use App\Http\Controllers\Controller;
use App\Http\Requests\ExamThresholdUpdate;
use Carbon\Carbon;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $exams = Exam::all();

        return view('dashboard.exam.index', compact('exams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $langs = CodingLang::all();

        return view('dashboard.exam.create', compact('langs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ExamStore $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(ExamStore $request)
    {
        $exam                 = new Exam();
        $exam->name           = $request->input('name');
        $exam->place          = $request->input('place');
        $exam->desc           = $request->input('desc') ?? '';
        $exam->time_start     = Carbon::parse($request->input('time_start'));
        $exam->time_end       = Carbon::parse($request->input('time_end'));
        $exam->signup_start   = Carbon::parse($request->input('signup_start'));
        $exam->signup_end     = Carbon::parse($request->input('signup_end'));
        $exam->pass_threshold = null;
        $exam->publish_time   = Carbon::parse($request->input('publish_time'));
        $exam->problem_note   = $request->input('problem_note') ?? '';
        $exam->save();

        $coding = [];

        foreach ($request->input('exam_lang') as $key => $exam_lang) {
            $coding[ $key ] = [
                'exam_id' => $exam->id,
                'lang_id' => $exam_lang,
            ];
        }

        return ExamCodingLang::insert($coding) ? redirect()->route('dashboard.exam.index')->with('msg',
            '建立考試成功') : redirect()->route('dashboard.exam.index')->with('error_msg', '建立考試失敗');

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $exam = Exam::findOrFail($id);

        $langs = ExamCodingLang::with('lang')->where('exam_id', $id)->get()->keyBy('lang_id');

        $signups = ExamSignup::whereExamId($exam->id)->get();
        $pc2     = ExamSignup::whereExamId($exam->id)->whereNotNull('pc2_account')->count();

        $data = $signups->groupBy(function ($item, $key) {
            return $item['solve_problem'];
        })->map(function ($item, $key) {
            return collect($item)->count();
        });

        return view('dashboard.exam.show', compact('exam', 'langs', 'signups', 'pc2', 'data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exam = Exam::findOrFail($id);

        $langs = CodingLang::all();

        $coding = ExamCodingLang::whereExamId($id)->get()->pluck('lang_id');

        return view('dashboard.exam.edit', compact('exam', 'langs', 'coding'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(ExamStore $request, $id)
    {
        $exam                 = Exam::findOrFail($id);
        $exam->name           = $request->input('name');
        $exam->place          = $request->input('place');
        $exam->desc           = $request->input('desc') ?? '';
        $exam->time_start     = Carbon::parse($request->input('time_start'));
        $exam->time_end       = Carbon::parse($request->input('time_end'));
        $exam->signup_start   = Carbon::parse($request->input('signup_start'));
        $exam->signup_end     = Carbon::parse($request->input('signup_end'));
        $exam->pass_threshold = $request->input('pass_threshold');
        $exam->publish_time   = Carbon::parse($request->input('publish_time'));
        $exam->problem_note   = $request->input('problem_note') ?? '';
        $exam->save();

        ExamCodingLang::whereExamId($id)->delete();

        $coding = [];
        foreach ($request->input('exam_lang') as $key => $exam_lang) {
            $coding[ $key ] = [
                'exam_id' => $exam->id,
                'lang_id' => $exam_lang,
            ];
        }

        return ExamCodingLang::insert($coding) ? redirect()->route('dashboard.exam.edit', $id)->with('msg',
            '更新考試成功') : redirect()->route('dashboard.exam.edit', $id)->with('error_msg', '更新考試失敗');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function update_threshold(ExamThresholdUpdate $request, $id)
    {
        $exam                 = Exam::findOrFail($id);
        $exam->pass_threshold = $request->input('pass_threshold');

        $msg = ['success' => 0, 'message' => '更新通過門檻失敗', 'status' => 'error'];
        if ($exam->save()) {
            $msg = ['success' => 1, 'message' => '更新通過門檻成功', 'status' => 'success'];
        }

        return response()->json($msg);;
    }
}

app/Http/Controllers/Dashboard/ExamExportController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Exam;
use App\ExamSignup;
use App\Http\Controllers\Controller;
use Excel;

class ExamExportController extends Controller
{
    public function index($id)
    {
        $exam    = Exam::findOrFail($id);
        $signups = ExamSignup::with(['school', 'dept', 'code'])->whereExamId($exam->id)->get();

        $lists = collect();
        $lists->push(['學校', '學系', '學制', '學號', '姓名', '程式語言', '報名時間']);

        foreach ($signups as $signup) {
            switch ($signup->edu_level) {
                case 'B':
                    $edu_level = '大學部';
                    break;
                case 'M':
                    $edu_level = '碩士班';
                    break;
                default:
                case 'D':
                    $edu_level = '博士班';
                    break;
            }
            $lists->push([
                $signup->school->name,
                $signup->dept->name,
                $edu_level,
                $signup->student_id,
                $signup->name_zh_tw,
                $signup->code->lang,
                $signup->created_at->toDateTimeString()
            ]);
        }
        $lists = $lists->toArray();

        Excel::create($exam->name . ' - 報名名單(' . now()->toDateTimeString() . ')', function ($excel) use ($lists, $exam){
            $excel->setTitle($exam->name . ' - 報名名單')
                ->setCreator(config('asiacode.site_name'))
                ->setCompany(config('asiacode.site_name'))
                ->setManager(config('asiacode.site_name'))
                ->setLastModifiedBy(config('asiacode.site_name'));

            $excel->sheet('報名名單', function ($sheet) use ($lists){
                $sheet->rows($lists)->setAutoSize(true);
            });
        })->export('xlsx');
    }


    public function pc2($id)
    {
        $exam = Exam::findOrFail($id);

        $this->generate_pc2($id);

        $signups = ExamSignup::with(['school', 'dept', 'code'])->whereExamId($exam->id)->get();


        $lists = collect();
        $lists->push([
            'site',
            'account',
            'displayname',
            'password',
            'group',
            'permdisplay',
            'permlogin',
            'externalid',
            'alias',
            'permpassword',
            'longschoolname',
            'shortschoolname',
            'countrycode'
        ]);

        foreach ($signups as $signup) {
            $lists->push([
                $exam->id,
                'team' . $signup->pc2_account,
                $signup->student_id,
                $signup->pc2_password,
                '',
                'TRUE',
                'TRUE',
                $exam->id*1000+$signup->pc2_account,
                $signup->student_id,
                'FALSE',
                '',
                '',
                'XXX'
            ]);
        }

        $lists = $lists->toArray();

        return response()
            ->view('dashboard.exam-export.pc2', compact('lists'), 200)
            ->header('Content-Disposition', 'attachment; filename="site'.$exam->id . '.txt"')
            ->header('Content-Type', 'text/plain');
    }

    protected function generate_pc2($id)
    {
        $exam = Exam::findOrFail($id);

        $signups = ExamSignup::whereExamId($exam->id)->get();

        $size    = count($signups);
        $numbers = range(1, $size);
        shuffle($numbers);

        $characters       = '23456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'; //去除 1, i, l, I, o, 0, O
        $characters_array = str_split($characters);


        foreach ($signups as $key => $signup) {
            $signup->pc2_account  = $numbers[ $key ];
            $signup->pc2_password = join('', array_random($characters_array, env('PC2_PASSWORD_LENGTH')));
            $signup->save();
        }

    }
}

resources/views/dashboard/exam/index.blade.php
@extends('layouts.app')

@section('page-title','考試管理')

@section('content')
	<div class="m-3">
		<a class="btn btn-primary" href="{{ route('dashboard.exam.create') }}">建立考試</a>
	</div>

	<table id="exam" class="table table-striped table-bordered">
		<thead>
		<tr>
			<th>#</th>
			<th>名稱</th>
			<th>報名時間</th>
			<th>考試時間</th>
			<th>操作</th>
		</tr>
		</thead>
		<tbody>
		@foreach($exams as $exam)
			<tr>
				<td>{{ $exam->id }}</td>
				<td>
					{{ $exam->name }}
				</td>
				<td>
					{{ $exam->signup_start->format('Y-m-d H:i') }} ~ {{ $exam->signup_end->format('Y-m-d H:i') }}
				</td>
				<td>
					{{ $exam->time_start->format('Y-m-d H:i') }} ~ {{ $exam->time_end->format('Y-m-d H:i') }}
				</td>
				<td>
					<a href="{{ route('dashboard.exam.edit',$exam->id) }}">修改</a>
					<a href="{{ route('dashboard.exam.show',$exam->id) }}">名單</a>
				</td>
			</tr>
		@endforeach
		</tbody>
	</table>
@endsection

@push('script')
	<script>
		$(function () {
			$('#exam').DataTable({
				processing: true,
				serverSide: true,
				ajax: '{{ route('api.exam.all') }}',
				columns: [
					{data: 'index'},
					{data: 'name'},
					{data: 'time'},
					{data: 'signup_time'},
					{data: 'action', name: 'action', orderable: false, searchable: false}
				],
				language: {
					"url": "{{ route('js.datatable') }}"
				}
			});
		});
	</script>
@endpush

resources/views/dashboard/exam/show.blade.php
@extends('layouts.app')

@section('page-title','考試名單')

@section('content')
	<h2 class="display-4">{{ $exam->name }}</h2>
	<hr class="my-4">
	<div>
		<i class="fas fa-map-marker-alt fa-fw"></i> 考試地點：{{ $exam->time_end }}
	</div>
	<div class="mb-3">
		<i class="fas fa-calendar-alt fa-fw"></i> 考試時間：{{ $exam->time_start }} ~ {{ $exam->time_end }}
	</div>
	<div class="card">
		<div class="card-body">
			{!! $exam->desc !!}
		</div>
	</div>
	<div class="mt-3 mb-3">
		<i class="fas fa-calendar-check"></i> 報名時間：{{ $exam->signup_start }} ~ {{ $exam->signup_end }}
	</div>

	@if( count($signups) != $pc2 )
		<div class="alert alert-danger">
			警告: 有報名者未有 PC<sup>2</sup> 帳號資訊
		</div>
	@endif

	@if( is_null($exam->pass_threshold) )
		<div class="alert alert-info">
			提示: 尚未設定通過門檻
		</div>
	@endif

	@includeWhen($errors->any(), 'component.alert-validation', ['errors' => $errors])

	<table class="table table-bordered text-center">
		<thead class="thead-dark">
		<tr>
			<th>報考人數</th>
			<th>PC<sup>2</sup> 產生人數</th>
			<th>PC<sup>2</sup> site</th>
			<th>平均題數</th>
			<th>通過門檻</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td>{{ count($signups) }}</td>
			<td>{{ $pc2 }}</td>
			<td>site{{ $exam->id }}</td>
			<td>{{ $signups->pluck('solve_problem')->avg() }}</td>
			<td>
				<div class="input-group">
					<input id="pass_threshold" type="text" class="form-control" placeholder="尚未設定通過門檻" value="{{ $exam->pass_threshold }}">
					<div class="input-group-append">
						<button id="update-threshold" class="btn btn-outline-secondary" type="button">設定</button>
					</div>
				</div>
			</td>
		</tr>
		</tbody>
	</table>

	<canvas id="myChart" height="80"></canvas>

	<div class="mt-3 mb-3">
		<a href="{{ route('dashboard.exam-export.list', $exam->id) }}" class="btn btn-success">匯出名單</a>
		<a data-toggle="collapse" href="#collapsePC2Team" class="btn btn-danger">產生 PC<sup>2</sup> 匯入檔</a>
		<a href="{{ route('dashboard.grade-ability.edit', $exam->id) }}" class="btn btn-outline-info">成績說明設定</a>
		<a href="#collapseScore" class="btn btn-outline-primary" data-toggle="collapse" role="button">成績匯入</a>
		@if( !is_null($exam->pass_threshold) )
			<a href="{{ route('dashboard.exam-score.cert', $exam->id) }}" class="btn btn-outline-danger">證書產生</a>
			<a href="{{ route('dashboard.exam-score.cert_file', $exam->id) }}" class="btn btn-outline-danger">證書檔案</a>
		@endif
	</div>

	<div id="accordion">
		<div id="collapsePC2Team" class="collapse" data-parent="#accordion">
			<div class="card card-body">
				<p>
					<a href="{{ route('dashboard.exam-export.pc2', $exam->id) }}" class="btn btn-danger" onclick="return confirm('是否產生?\n注意:若之前有產生將會覆蓋!!')">下載 PC<sup>2</sup> 匯入檔</a>
				</p>

				<figure class="figure text-center">
					<img src="{{ asset('img/team-generate-1.PNG') }}" class="figure-img img-fluid rounded" alt="">
					<figcaption class="figure-caption text-center">1. 在開啟時，請先確認開啟的站點是否為
						<span class="badge badge-success">site{{ $exam->id }}</span></figcaption>
					<figcaption class="figure-caption text-center">2. 點擊
						<span class="badge badge-info">Generate</span> 按鈕
					</figcaption>
				</figure>
				<figure class="figure text-center">
					<img src="{{ asset('img/team-generate-2.PNG') }}" class="figure-img img-fluid rounded" alt="">
					<figcaption class="figure-caption text-center">3. 在匯入前，請先產生
						<span class="badge badge-success">{{ count($signups) }}</span> 個 team 帳號
					</figcaption>
				</figure>
				<figure class="figure text-center">
					<img src="{{ asset('img/team-generate-3.PNG') }}" class="figure-img img-fluid rounded" alt="">
					<figcaption class="figure-caption text-center">4. 點擊
						<span class="badge badge-info">Load</span> 按鈕，匯入帳號，並選擇系統(<span class="badge badge-success">site{{ $exam->id }}.txt</span>)產生的檔案匯入
					</figcaption>
				</figure>
				<figure class="figure text-center">
					<img src="{{ asset('img/team-generate-4.PNG') }}" class="figure-img img-fluid rounded" alt="">
					<figcaption class="figure-caption text-center">5. PC<sup>2</sup> 會看到匯入的名單，確認沒問題後，點擊
						<span class="badge badge-info">Accept</span> 按鈕，完成匯入
					</figcaption>
				</figure>
			</div>
		</div>
		<div id="collapseScore" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
			<div class="card card-body">
				<form method="POST" action="{{ route('dashboard.exam-score.index', $exam->id) }}" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="card card-body">
						<input name="score" type="file">
						<div class="text-center">
							<button class="btn btn-primary" type="submit">上傳成績檔</button>
						</div>
					</div>
				</form>
				<div class="mb-3"></div>
				<figure class="figure text-center">
					<img src="{{ asset('img/score-1.PNG') }}" class="figure-img img-fluid rounded" alt="">
					<figcaption class="figure-caption text-center">1. 選擇
						<span class="badge badge-primary">Reports</span></figcaption>
					<figcaption class="figure-caption text-center">2. 下拉清單選項選擇
						<span class="badge badge-info">Standings Web Pages</span> 按鈕
					</figcaption>
					<figcaption class="figure-caption text-center">3. 點擊
						<span class="badge badge-info">Generate Summary</span> 按鈕
					</figcaption>
				</figure>
				<figure class="figure text-center">
					<img src="{{ asset('img/score-2.PNG') }}" class="figure-img img-fluid rounded" alt="">
					<figcaption class="figure-caption text-center">4. 開啟 PC<sup>2</sup>下的,
						<span class="badge badge-primary">reports</span> 資料夾
					</figcaption>
					<figcaption class="figure-caption text-center">5. 將
						<span class="badge badge-primary">report.Standings_Web_Pages.pc2export(...).html</span> 檔案上傳至系統
					</figcaption>
				</figure>
			</div>
		</div>
	</div>

	<table id="exam" class="table table-striped">
		<thead>
		<tr>
			<th>#</th>
			<th>學號</th>
			<th>名字</th>
			<th>英文名字</th>
			<th>報考語言</th>
			<th>完成題數</th>
			<th>報名時間</th>
		</tr>
		</thead>
	</table>

@endsection

@push('js')
	<script src="{{ asset('js/Chart.js') }}"></script>
@endpush

@push('script')
	<script>
		$(function () {
			$('#exam').DataTable({
				processing: true,
				serverSide: true,
				stateSave: true,
				ajax: '{{ route('api.signup',$exam->id) }}',
				columns: [
					{data: 'index'},
					{data: 'student_id'},
					{data: 'name_zh_tw'},
					{data: 'name_en'},
					{data: 'lang'},
					{data: 'solve_problem'},
					{data: 'created_at'},
				],
				"language": {
					"url": "{{ route('js.datatable') }}"
				}
			});

			$('#update-threshold').click(function () {
				axios.post('{{ route('dashboard.exam.threshold',$exam->id) }}', {pass_threshold: $('#pass_threshold').val()})
					.then((response) => {
						if (response.status === 200) {
							if (response.data.success) {
								swal(response.data.message, '', response.data.status);
							} else {
								swal('發生錯誤', response.data.message, 'warning');
							}
						} else if (response.status === 422) {
							swal('Error!', response.data.errors.solve_problem, 'warning');
						}
					})
					.catch((error) => {
						swal('發生錯誤', 'error', 'warning');
					});
			});

			new Chart($("#myChart"), {
				"type": "pie",
				"data": {
					"labels": @json(array_keys($data->toArray())),
					"datasets": [{
						"label":"解題題數",
						"data": @json(array_values($data->toArray())),
						"fill": false,
						"backgroundColor": ["rgba(255, 99, 132, 0.2)", "rgba(255, 159, 64, 0.2)", "rgba(255, 205, 86, 0.2)", "rgba(75, 192, 192, 0.2)", "rgba(54, 162, 235, 0.2)", "rgba(153, 102, 255, 0.2)", "rgba(201, 203, 207, 0.2)"],
						"borderColor": ["rgb(255, 99, 132)", "rgb(255, 159, 64)", "rgb(255, 205, 86)", "rgb(75, 192, 192)", "rgb(54, 162, 235)", "rgb(153, 102, 255)", "rgb(201, 203, 207)"],
						"borderWidth": 1
					}]
				},
				"options": {
					responsive: true,
					title: {
						display: true,
						text: '解題題數'
					}
				}
			});

		});
	</script>
@endpush