routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ExamController@index')->name('home');
Route::get('home', 'ExamController@index')->name('home.index');
Route::get('exam', 'ExamController@index')->name('exam.index');
Route::get('show/{id}', 'ExamController@show')->name('exam.show');
Route::get('cert/{key}', 'CertController@show')->name('cert.index');
Route::post('cert/{key}', 'CertController@verify')->name('cert.verify');
Route::get('problem', 'ProblemController@index')->name('problem.index');
Route::get('problem/{id}', 'ProblemController@show')->name('problem.show');

/**
 * Member
 */
Route::group([
    'middleware' => ['auth'],
], function (){
    Route::post('exam/{id}/signup', 'ExamController@store')->name('exam.store');
    //    Route::get('exam/{id}/certificate', 'ExamController@certificate')->name('exam.certificate');
    Route::get('exam/{id}/cancel', 'ExamController@cancel')->name('exam.cancel');
    Route::get('profile', 'PorfileController@index')->name('profile.index');
    Route::post('profile/passwd', 'PorfileController@passwd')->name('profile.passwd');
});

/**
 * Authentication Routes
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('email-verification/error',
    'Auth\RegisterController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}',
    'Auth\RegisterController@getVerification')->name('email-verification.check');

/**
 * API
 */
Route::group([
    'prefix'    => 'api',
    'as'        => 'api.',
    'namespace' => 'Api'
], function (){
    Route::get('exam', 'ExamController@all')->name('exam');
    Route::get('dept', 'DeptController@get')->name('dept');
    Route::get('problem', 'ProblemController@all')->name('problem');
});


/**
 * Dashboard
 */
Route::group([
    'middleware' => ['auth', 'role:admin'],
], function (){
    Route::get('api/signup/{id}', 'Api\ExamController@signup')->name('api.signup')->where('id', '[0-9]+');
    Route::get('api/user/all', 'Api\UserController@all')->name('api.user.all');
    Route::get('api/school/all', 'Api\SchoolController@all')->name('api.school.all');
    Route::get('api/problems', 'Api\ProblemController@dashboard')->name('api.problem.all');
    Route::get('api/exams', 'Api\ExamController@admin')->name('api.exam.all');

    Route::group([
        'prefix'    => 'dashboard',
        'as'        => 'dashboard.',
        'namespace' => 'Dashboard'
    ], function (){
        Route::post('exam/threshold/{id}', 'ExamController@update_threshold')->name('exam.threshold')->where('id',
            '[0-9]+');

        Route::get('exam-export/list/{id}', 'ExamExportController@index')->name('exam-export.list');
        Route::get('exam-export/pc2/{id}', 'ExamExportController@pc2')->name('exam-export.pc2');

        Route::post('exam/score/enter/{id}', 'ExamScoreController@index')->name('exam-score.index');
        Route::post('exam/score/update/{id}', 'ExamScoreController@store')->name('exam-score.store');
        Route::get('exam/score/cert/{id}', 'ExamScoreController@cert')->name('exam-score.cert');
        Route::get('exam/cert/{id}', 'ExamScoreController@cert_file')->name('exam-score.cert_file');

        Route::resource('grade-ability', 'GradeAbilityController')->only(['edit', 'update']);
        Route::resource('exam-problem', 'ExamProblemController',
            ['parameters' => ['exam-problem' => 'id']])->only(['show', 'update', 'destroy']);
        Route::resource('exam', 'ExamController');
        Route::resource('user', 'UserController');
        Route::resource('school', 'SchoolController');
        Route::resource('problem', 'ProblemController')->only(['index', 'show']);
    });

});

Route::get('datatable', 'DatatableController')->name('js.datatable');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Http/Controllers/Dashboard/ExamController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\CodingLang;
use App\Exam;
use App\ExamCodingLang;
use App\ExamSignup;
use App\Http\Requests\ExamStore;
use App\Http\Controllers\Controller;
use App\Http\Requests\ExamThresholdUpdate;
use Carbon\Carbon;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $exams = Exam::all();

        return view('dashboard.exam.index', compact('exams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $langs = CodingLang::all();

        return view('dashboard.exam.create', compact('langs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ExamStore $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(ExamStore $request)
    {
        $exam                 = new Exam();
        $exam->name           = $request->input('name');
        $exam->place          = $request->input('place');
        $exam->desc           = $request->input('desc') ?? '';
        $exam->time_start     = Carbon::parse($request->input('time_start'));
        $exam->time_end       = Carbon::parse($request->input('time_end'));
        $exam->signup_start   = Carbon::parse($request->input('signup_start'));
        $exam->signup_end     = Carbon::parse($request->input('signup_end'));
        $exam->pass_threshold = null;
        $exam->publish_time   = Carbon::parse($request->input('publish_time'));
        $exam->problem_note   = $request->input('problem_note') ?? '';
        $exam->save();

        $coding = [];

        foreach ($request->input('exam_lang') as $key => $exam_lang) {
            $coding[ $key ] = [
                'exam_id' => $exam->id,
                'lang_id' => $exam_lang,
            ];
        }

        return ExamCodingLang::insert($coding) ? redirect()->route('dashboard.exam.index')->with('msg',
            '建立考試成功') : redirect()->route('dashboard.exam.index')->with('error_msg', '建立考試失敗');

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $exam = Exam::findOrFail($id);

        $langs = ExamCodingLang::with('lang')->where('exam_id', $id)->get()->keyBy('lang_id');

        $signups = ExamSignup::whereExamId($exam->id)->get();
        $pc2     = ExamSignup::whereExamId($exam->id)->whereNotNull('pc2_account')->count();

        $data = $signups->groupBy(function ($item, $key) {
            return $item['solve_problem'];
        })->map(function ($item, $key) {
            return collect($item)->count();
        });

        return view('dashboard.exam.show', compact('exam', 'langs', 'signups', 'pc2', 'data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exam = Exam::findOrFail($id);

        $langs = CodingLang::all();

        $coding = ExamCodingLang::whereExamId($id)->get()->pluck('lang_id');

        return view('dashboard.exam.edit', compact('exam', 'langs', 'coding'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(ExamStore $request, $id)
    {
        $exam                 = Exam::findOrFail($id);
        $exam->name           = $request->input('name');
        $exam->place          = $request->input('place');
        $exam->desc           = $request->input('desc') ?? '';
        $exam->time_start     = Carbon::parse($request->input('time_start'));
        $exam->time_end       = Carbon::parse($request->input('time_end'));
        $exam->signup_start   = Carbon::parse($request->input('signup_start'));
        $exam->signup_end     = Carbon::parse($request->input('signup_end'));
        $exam->pass_threshold = $request->input('pass_threshold');
        $exam->publish_time   = Carbon::parse($request->input('publish_time'));
        $exam->problem_note   = $request->input('problem_note') ?? '';
        $exam->save();

        ExamCodingLang::whereExamId($id)->delete();

        $coding = [];
        foreach ($request->input('exam_lang') as $key => $exam_lang) {
            $coding[ $key ] = [
                'exam_id' => $exam->id,
                'lang_id' => $exam_lang,
            ];
        }

        return ExamCodingLang::insert($coding) ? redirect()->route('dashboard.exam.edit', $id)->with('msg',
            '更新考試成功') : redirect()->route('dashboard.exam.edit', $id)->with('error_msg', '更新考試失敗');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function update_threshold(ExamThresholdUpdate $request, $id)
    {
        $exam                 = Exam::findOrFail($id);
        $exam->pass_threshold = $request->input('pass_threshold');

        $msg = ['success' => 0, 'message' => '更新通過門檻失敗', 'status' => 'error'];
        if ($exam->save()) {
            $msg = ['success' => 1, 'message' => '更新通過門檻成功', 'status' => 'success'];
        }

        return response()->json($msg);;
    }
}

app/Http/Controllers/Dashboard/ExamExportController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Exam;
use App\ExamSignup;
use App\Http\Controllers\Controller;
use Excel;

class ExamExportController extends Controller
{
    public function index($id)
    {
        $exam    = Exam::findOrFail($id);
        $signups = ExamSignup::with(['school', 'dept', 'code'])->whereExamId($exam->id)->get();

        $lists = collect();
        $lists->push(['學校', '學系', '學制', '學號', '姓名', '程式語言', '報名時間']);

        foreach ($signups as $signup) {
            switch ($signup->edu_level) {
                case 'B':
                    $edu_level = '大學部';
                    break;
                case 'M':
                    $edu_level = '碩士班';
                    break;
                default:
                case 'D':
                    $edu_level = '博士班';
                    break;
            }
            $lists->push([
                $signup->school->name,
                $signup->dept->name,
                $edu_level,
                $signup->student_id,
                $signup->name_zh_tw,
                $signup->code->lang,
                $signup->created_at->toDateTimeString()
            ]);
        }
        $lists = $lists->toArray();

        Excel::create($exam->name . ' - 報名名單(' . now()->toDateTimeString() . ')', function ($excel) use ($lists, $exam){
            $excel->setTitle($exam->name . ' - 報名名單')
                ->setCreator(config('asiacode.site_name'))
                ->setCompany(config('asiacode.site_name'))
                ->setManager(config('asiacode.site_name'))
                ->setLastModifiedBy(config('asiacode.site_name'));

            $excel->sheet('報名名單', function ($sheet) use ($lists){
                $sheet->rows($lists)->setAutoSize(true);
            });
        })->export('xlsx');
    }


    public function pc2($id)
    {
        $exam = Exam::findOrFail($id);

        $this->generate_pc2($id);

        $signups = ExamSignup::with(['school', 'dept', 'code'])->whereExamId($exam->id)->get();


        $lists = collect();
        $lists->push([
            'site',
            'account',
            'displayname',
            'password',
            'group',
            'permdisplay',
            'permlogin',
            'externalid',
            'alias',
            'permpassword',
            'longschoolname',
            'shortschoolname',
            'countrycode'
        ]);

        foreach ($signups as $signup) {
            $lists->push([
                $exam->id,
                'team' . $signup->pc2_account,
                $signup->student_id,
                $signup->pc2_password,
                '',
                'TRUE',
                'TRUE',
                $exam->id*1000+$signup->pc2_account,
                $signup->student_id,
                'FALSE',
                '',
                '',
                'XXX'
            ]);
        }

        $lists = $lists->toArray();

        return response()
            ->view('dashboard.exam-export.pc2', compact('lists'), 200)
            ->header('Content-Disposition', 'attachment; filename="site'.$exam->id . '.txt"')
            ->header('Content-Type', 'text/plain');
    }

    protected function generate_pc2($id)
    {
        $exam = Exam::findOrFail($id);

        $signups = ExamSignup::whereExamId($exam->id)->get();

        $size    = count($signups);
        $numbers = range(1, $size);
        shuffle($numbers);

        $characters       = '23456789abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'; //去除 1, i, l, I, o, 0, O
        $characters_array = str_split($characters);


        foreach ($signups as $key => $signup) {
            $signup->pc2_account  = $numbers[ $key ];
            $signup->pc2_password = join('', array_random($characters_array, env('PC2_PASSWORD_LENGTH')));
            $signup->save();
        }

    }
}

app/Http/Controllers/Dashboard/ExamProblemController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Exam;
use App\ExamProblem;
use App\Problem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ExamProblemController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $exam = Exam::findOrFail($id);
        $problems = Problem::all();
        $exam_problems = ExamProblem::with('problem')->whereExamId($id)->get();

        $problem_id =  $exam_problems->pluck('problem_id');
        $show = [];
        foreach ($problem_id as $pid){
            $show[$pid] = true;
        }

        return view('dashboard.exam-problem.show', compact('exam','exam_problems', 'problems','show'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $exam = Exam::findOrFail($id);

        foreach ($request->input('problem_id') as $problem_id){
            ExamProblem::create([
                'exam_id' => $exam->id,
                'problem_id' => $problem_id,
            ]);
        }

        return redirect()->route('dashboard.exam-problem.show', $exam->id)->with('msg', '考試題目設定完畢');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $msg = ['success' => 0, 'message' => '刪除考試題目失敗', 'status' => 'error'];
        $exam = Exam::whereId($id)->first();

        if (empty($exam)) {
            return response()->json($msg);
        }

        if( ExamProblem::whereExamId($exam->id)->whereProblemId($request->query('problem_id'))->delete() ){
            $msg = ['success' => 1, 'message' => '成功刪除考試題目', 'status' => 'success'];
        }else{
            $msg = ['success' => 0, 'message' => '刪除考試題目失敗', 'status' => 'error'];
        }

        return response()->json($msg);
    }
}

resources/views/dashboard/grade-ability/edit.blade.php
@extends('layouts.app')

@section('page-title','成績說明設定：'.$exam->name)

@section('content')
	<h2 class="display-4">{{ $exam->name }}</h2>
	<hr class="my-4">
	<div>
		<i class="fas fa-map-marker-alt fa-fw"></i> 考試地點：{{ $exam->time_end }}
	</div>
	<div class="mb-3">
		<i class="fas fa-calendar-alt fa-fw"></i> 考試時間：{{ $exam->time_start->format('Y-m-d H:i') }} ~ {{ $exam->time_end->format('Y-m-d H:i') }}
	</div>
	<div class="mt-3 mb-3">
		<i class="fas fa-calendar-check"></i> 報名時間：{{ $exam->signup_start->format('Y-m-d H:i') }} ~ {{ $exam->signup_end->format('Y-m-d H:i') }}
	</div>
	<div class="card">
		<div class="card-body">
			{!! $exam->desc !!}
		</div>
	</div>

	@if( is_null($exam->pass_threshold) )
		<div class="alert alert-info">
			提示: 尚未設定通過門檻
		</div>
	@endif

	<div class="mt-3 mb-3">
		<a href="{{ route('dashboard.exam.show', $exam->id) }}" class="btn btn-outline-primary" role="button">成績匯入</a>
		<a href="{{ route('dashboard.exam-export.list', $exam->id) }}" class="btn btn-success">匯出名單</a>
		<a href="{{ route('dashboard.grade-ability.edit', $exam->id) }}" class="btn btn-outline-info">成績說明設定</a>
	</div>

	<hr>

	<form method="POST" action="{{ route('dashboard.grade-ability.update', $exam->id) }}">
		{{ csrf_field() }}
		{{ method_field('PUT') }}
		<div class="form-group">
			<label for="slug">證照階級代碼*</label>
			<input id="slug" type="text" size="5" class="form-control {{ $errors->has('slug') ? 'is-invalid' : '' }}" name="slug" value="{{ old('slug',optional($grade)->slug) }}" required autofocus>
			@if ($errors->has('slug'))
				<div class="invalid-feedback"> {{ $errors->first('slug') }} </div>
			@endif
		</div>
		<div class="form-group">
			<label for="cert_title_en">證照英文標題*</label>
			<input id="cert_title_en" type="text" class="form-control {{ $errors->has('cert_title_en') ? 'is-invalid' : '' }}" name="cert_title_en" value="{{ old('cert_title_en',optional($grade)->cert_title_en) }}" required>
			@if ($errors->has('cert_title_en'))
				<div class="invalid-feedback"> {{ $errors->first('cert_title_en') }} </div>
			@endif
			<p class="text-info">取代代碼: <code>{code}</code> 系統可以轉換為報名者報名程式語言 </p>
		</div>
		<div class="form-group">
			<label for="cert_title_zh_tw">證照中文標題*</label>
			<input id="cert_title_zh_tw" type="text" class="form-control {{ $errors->has('cert_title_zh_tw') ? 'is-invalid' : '' }}" name="cert_title_zh_tw" value="{{ old('cert_title_zh_tw',optional($grade)->cert_title_zh_tw) }}" required>
			@if ($errors->has('cert_title_zh_tw'))
				<div class="invalid-feedback"> {{ $errors->first('cert_title_zh_tw') }} </div>
			@endif
			<p class="text-info">取代代碼: <code>{code}</code> 系統可以轉換為報名者報名程式語言 </p>
		</div>
		<div class="form-group">
			<label for="desc">能力指標說明*</label>
			<textarea id="desc" name="desc" class="form-control {{ $errors->has('desc') ? 'is-invalid' : '' }}">{{ old('desc',optional($grade)->desc) }}</textarea>
			@if ($errors->has('desc'))
				<div class="invalid-feedback"> {{ $errors->first('desc') }} </div>
			@endif
		</div>

		<button type="submit" class="btn btn-info">儲存</button>
	</form>

@endsection

@push('js')

@endpush

@push('js')
	<script src="//cdn.ckeditor.com/4.8.0/full/ckeditor.js"></script>
	<script src="//cdn.ckeditor.com/4.8.0/full/adapters/jquery.js"></script>
@endpush

@push('script')
	<script>
		$(function () {
			$('textarea#desc').ckeditor({
				toolbarGroups: [
					{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
					{ name: 'colors', groups: [ 'colors' ] },
					{ name: 'links', groups: [ 'links' ] },
					{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
					{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
				],
				enterMode: CKEDITOR.ENTER_BR,
				removeButtons: 'ShowBlocks,Maximize,About,Styles,Format,Font,FontSize,Image,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,BidiLtr,BidiRtl,Language,Blockquote,CreateDiv,CopyFormatting,Source,Save,NewPage,Preview,Print,Templates,Cut,Copy,Paste,PasteText,PasteFromWord,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,Replace,Find,SelectAll,Scayt,Anchor',
			});
		});
	</script>
@endpush